=== mikhailbolshakov/camunda/schema/user-task-message-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": ["header", "processContext", "taskContext", "variables"],
  "properties": {

    "header": {
      "$ref": "common/header-schema.json"
    },

    "processContext": {
      "$ref": "common/process-context-schema.json"
    },

    "taskContext": {
      "$ref": "common/task-context-schema.json"
    },

    "userContext": {
      "$ref": "common/user-task-context-schema.json"
    },

    "variables": {
      "$ref": "common/variables-schema.json"
    }

  }
}

=== mikhailbolshakov/camunda/schema/examples/user-task-example.json
{
  "header": {
    "messageId": "875fbe7d-9839-4409-93a8-527dd51de1f6",
    "schemaVersion": "1.0.0",
    "timestamp": "2020-01-01T18:30:00.000Z"
  },
  "processContext": {
    "processDefId": "rgs.med.mk-consultation",
    "processId" : "a06f20a7-fb64-4d48-9cc7-cbe86ebac542"
  },
  "taskContext": {
    "taskDefId": "input-registration-data",
    "taskId": "3232453253"
  },
  "userContext": {
    "formId": "rgs.med.mk-consultation.input-registration-data",
    "assignedUserId": "bb047337-6863-4296-8bd5-4a7ec5803ffe"
  },
  "variables": {

  }
}

=== mikhailbolshakov/camunda/schema/examples/service-task-example.json
{
  "header": {
    "messageId": "875fbe7d-9839-4409-93a8-527dd51de1f6",
    "schemaVersion": "1.0.0",
    "timestamp": "2020-01-01T18:30:00.000Z"
  },
  "processContext": {
    "processDefId": "rgs.med.mk-consultation",
    "processId" : "a06f20a7-fb64-4d48-9cc7-cbe86ebac542"
  },
  "taskContext": {
    "taskDefId": "assign-mk",
    "taskId": "3232453253"
  },
  "variables": {
  }
}
